### ISSUE TITLE
Support for HLint.hs config file

### ISSUE THREAD

**Issue by creichert** [pbrisbin/codeclimate-hlint#10]
Does the hlint engine recognize an `HLint.hs` file the repo root? It doesn't seem to but I could be missing something.

**Comment by pbrisbin** [comment]
Unfortunately, it is not currently supported.

I'd consider it a minor mistake that this engine currently imports HLint library code and runs the linter directly. This means some of the CLI behavior (including options handling, locating/using a local `HLint.hs`) aren't inherited by the engine.

Our options are to re-build that logic in the engine, or transition to running the `hlint` executable itself with some sort of JSON output / translator. The latter sounds better, but the main issue there is maintaining the streaming nature of the engine, since we want don't want to wait for the engine to complete and output all the issues at the end.

**Comment by creichert** [comment]
@pbrisbin Got it, thanks for the reply. I'll use code-climate a bit more and see if this is really a blocker. Most of the warnings were cosmetic anyways.

**Comment by creichert** [comment]
In case anyone else hits this, you can disable specific checks using code-climate specific features:

For example:

```
engines:
  hlint:
    enabled: true
    checks:
      HLint/RedundantDo:
        enabled: false
      HLint/RedundantBracket:
        enabled: false
```

When analyzing the checks, look for "Disable check" and you will be shown the correct configuration option.
